language: csharp
solution: Multiformats.Hash.sln
notifications:
  email: false
branches:
  only:
    - master
install:
  - nuget restore Multiformats.Hash/packages.config -PackagesDirectory ./packages
  - nuget restore Multiformats.Hash.Tests/packages.config -PackagesDirectory ./packages
  - mkdir ./sharness
  - git clone https://github.com/multiformats/multihash.git ./sharness
  - echo -e "#!/bin/bash\nmono ./Multiformats.Hash.CLI/bin/Release/multihash.exe" >./multihash
  - chmod +x ./multihash
env:
  - MULTIHASH_BIN="/home/travis/build/multiformats/cs-multihash/multihash"
script:
  - xbuild /p:Configuration=Release Multiformats.Hash.sln
  - mono ./packages/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./Multiformats.Hash.Tests/bin/Release/Multiformats.Hash.Tests.dll
  - make -j1 -C ./sharness/tests/sharness
cache:
  - directories:
    - ./packages