language: csharp
solution: Multiformats.Hash.sln
notifications:
  email: false
branches:
  only:
    - master
install:
  - nuget restore Multiformats.Hash/packages.config -PackagesDirectory ./packages
  - nuget restore Multiformats.Hash.Tests/packages.config -PackagesDirectory ./packages
  - mkdir ./sharness
  - git clone https://github.com/multiformats/multihash.git ./sharness
  - chmod +x ./multihash
env:
  - TEST_EXPENSIVE=1
  - MULTIHASH_BIN="/home/travis/build/multiformats/cs-multihash/multihash"
script:
  - xbuild /p:Configuration=Release /p:Platform=x64 Multiformats.Hash.sln
  - ./multihash --version
  - mono ./packages/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./Multiformats.Hash.Tests/bin/x64/Release/Multiformats.Hash.Tests.dll
  - make -j1 -C ./sharness/tests/sharness
cache:
  - directories:
    - ./packages